# 6、KNN人力资源实战

"Adults"数据集是一个经典的机器学习数据集，用于分类任务。该数据集基于1994年美国人口普查的数据，包含来自美国人口普查局的个人收入数据，旨在预测一个人的收入是否高于50K美元/年。该数据集由多个特征(包括年龄、教育程度、婚姻状况、职业等)组成，其中一些特征是连续值，另一些类别值。

| 字段 | 中文 | 说明 |
| :--- | :--- | :--- |
| age | 年龄 | 被调查者的年龄。它是一个连续值特征 |
| workclass | 工作类型 | 工作类型是被调查者的雇佣类型 |
| final_weight | 权重 | 数值型数据，指定一个人在人口普查中所代表的人口数量 |
| education | 学历 | 学历是被调查者的教育水平 |
| education_num | 受教育年数 | 是被调查者接受教育的年数 |
| marital_status | 婚姻状况 | 被调查者的婚姻状况 |
| occupation | 职业 | 调查者的工作职业 |
| relationship | 家庭关系 | 家庭关系是被调查者和家庭成员之间的关系 |
| race | 种族 | 被调查者的种族 |
| sex | 性别 | 性别 |
| capital_gain | 资本收益 | 是指个人在一段时间内从投资或者资产出售中获取的利润 |
| capital_loss | 资本损失 | 是指个人在一段时间内因投资或者资产出售而产生的亏损 |
| hours_per_week | 工作时长 | 每周工作时长，数值型数据 |
| native_country | 原生国家 | 原生国家 |
| salary | 薪资 | 表示一个人的年收入是否高于50K美元，包括 <=50K 和 >50K 两种分类。 |

KNN算法建模：

- 数据处理，字符串类型数据…>数值型数据

- 空数据删除

- 异常值删除

- 模型调优

## 6.1.1、数据加载

In [1]:
import numpy as np

import pandas as pd

from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score #准确率

from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import MinMaxScaler,LabelEncoder #标然编码

In [2]:
data = pd.read_csv('./adults.txt')
display(data.head(), data.shape)

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0

(32561, 15)

## 6.1.2、数据预处理

In [3]:
#空数据处理
data.isna().sum()

age               0
workclass         0
final-weight      0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
salary            0
dtype: int64

In [4]:
data['workclass'].unique()

array([7, 6, 4, 1, 2, 0, 5, 8, 3])

In [5]:
data = data.replace('?', np.nan).dropna().reset_index(drop = True)
data.shape

(32561, 15)

In [6]:
# 异常值，算法建模不是好数据
data['capital-gain'].sort_values(ascending=False).unique()

array([99999, 41310, 34095, 27828, 25236, 25124, 22040, 20051, 18481,
       15831, 15024, 15020, 14344, 14084, 13550, 11678, 10605, 10566,
       10520,  9562,  9386,  8614,  7978,  7896,  7688,  7443,  7430,
        7298,  6849,  6767,  6723,  6514,  6497,  6418,  6360,  6097,
        5721,  5556,  5455,  5178,  5060,  5013,  4934,  4931,  4865,
        4787,  4687,  4650,  4508,  4416,  4386,  4101,  4064,  3942,
        3908,  3887,  3818,  3781,  3674,  3471,  3464,  3456,  3432,
        3418,  3411,  3325,  3273,  3137,  3103,  2993,  2977,  2964,
        2961,  2936,  2907,  2885,  2829,  2653,  2635,  2597,  2580,
        2538,  2463,  2414,  2407,  2387,  2354,  2346,  2329,  2290,
        2228,  2202,  2176,  2174,  2105,  2062,  2050,  2036,  2009,
        1848,  1831,  1797,  1639,  1506,  1471,  1455,  1424,  1409,
        1173,  1151,  1111,  1086,  1055,   991,   914,   594,   401,
         114,     0])

In [7]:
data['capital-loss'].sort_values(ascending=False).unique()

array([4356, 3900, 3770, 3683, 3004, 2824, 2754, 2603, 2559, 2547, 2489,
       2472, 2467, 2457, 2444, 2415, 2392, 2377, 2352, 2339, 2282, 2267,
       2258, 2246, 2238, 2231, 2206, 2205, 2201, 2179, 2174, 2163, 2149,
       2129, 2080, 2057, 2051, 2042, 2002, 2001, 1980, 1977, 1974, 1944,
       1902, 1887, 1876, 1848, 1844, 1825, 1816, 1762, 1755, 1741, 1740,
       1735, 1726, 1721, 1719, 1672, 1669, 1668, 1651, 1648, 1628, 1617,
       1602, 1594, 1590, 1579, 1573, 1564, 1539, 1504, 1485, 1411, 1408,
       1380, 1340, 1258, 1138, 1092,  974,  880,  810,  653,  625,  419,
        323,  213,  155,    0])

In [8]:
cond =(data['capital-gain'] != 99999) & (data['capital-loss'] != 4356)
data = data[cond]
data.shape

(32399, 15)

## 6.1.3、建模预测

In [9]:
le = LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
le.transform(["paris", "paris", "tokyo", "amsterdam"])

array([1, 1, 2, 0])

In [10]:
columns = ['workclass', 'education', 'marital-status', 'occupation', 'race', 'sex', 'native-country']
le = LabelEncoder()
for col in columns:
    data[col] = le.fit_transform(data[col])
data.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0

In [11]:
# 归一化 最大值最小值归一化
scaler = MinMaxScaler()
col_norm = ['age', 'final-weight', 'workclass', 'education-num', 'education', 'marital-status', 'occupation',
            'relationship', 'race', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']
data[col_norm] = scaler.fit_transform(data[col_norm])
data.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,0.301370,0.875,0.044302,0.600000,0.800000,0.666667,0.071429,0.2,1.0,1,0.052626,0.0,0.397959,0.951220,0
1,0.452055,0.750,0.048238,0.600000,0.800000,0.333333,0.285714,0.0,1.0,1,0.000000,0.0,0.122449,0.951220,0
2,0.287671,0.500,0.138113,0.733333,0.533333,0.000000,0.428571,0.2,1.0,1,0.000000,0.0,0.397959,0.951220,0
3,0.493151,0.500,0.151068,0.066667,0.400000,0.333333,0.428571,0.0,0.5,1,0.000000,0.0,0.397959,0.951220,0
4,0.150685,0.500,0.221488,0.600000,0.800000,0.333333,0.714286,1.0,0.5,0,0.000000,0.0,0.397959,0.121951,0

## 6.1.4、数据拆分

In [12]:
# 6.3 数据拆分
y = data['salary']
X = data.drop(labels='salary', axis=1)
X.shape

(32399, 14)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1024)

## 6.1.5、建模预测

In [14]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print('真实值：', y_test[:20].values)
print('预测值：', y_pred[:20])

真实值： [0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0]
预测值： [0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0]

In [15]:
accuracy_score(y_test, y_pred)

0.8257716049382716

## 6.1.6、模型调优

In [ ]:
%%time
knn = KNeighborsClassifier()

params = dict(n_neighbors=[3, 5, 9, 15, 23, 31, 39],
              weights=['uniform', 'distance'], p=[1, 2])

gCV = GridSearchCV(knn, params, cv=5)
gCV.fit(X_train, y_train)

In [ ]:
gCV.best_params_

{'n_neighbors': 31, 'p': 1, 'weights': 'uniform'}

In [ ]:
knn_best = gCV.best_estimator_
knn_best.score(X_test, y_test)

0.8371913580246914

In [ ]:
gCV.score(X_test,y_test)

0.8371913580246914