# 1. Pandas 核心数据类型

## 1.1 什么是Pandas

- Pandas是Python语言的一个扩展程序库，用于数据分析。
- Pandas是一个开放源码、BSD许可的库，提供高性能、易于使用的数据结构和数据分析工具。
- Pandas名字衍生自术语"panel data"（面板数据）和"Python data analysis"（Python数据分析）。
- Pandas一个强大的分析结构化数据的工具集，基础是Numpy（提供高性能的矩阵运算）。
- Pandas可以从各种文件格式比如CSV、JSON、SQL、Microsoft Excel导入数据。
- Pandas可以对各种数据进行运算操作，比如归并、再成形、选择，还有数据清洗和数据加工特征。

Pandas的主要数据结构是Series（一维数据）与DataFrame（二维数据），这两种数据结构足以处理金融、统计、社会科学、工程等领域里的大多数典型用例

## 1.2 Series

Series是一种类似于字典(dict-like)的一维数组(array-like)的对象，由下面两个部分组成:

- values:-组数据(ndarray类型)

- index:相关的数据索引标签

In [1]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame

### 1.2.1 构造Series

1. From ndarray 使用ndarray构造 是一个引用对象

In [5]:
arr1 = np.random.randint(0, 10, size=5)
arr1

array([6, 8, 6, 9, 1], dtype=int32)

In [11]:
arr1[0] = 100

In [12]:
s1 = pd.Series(data=arr1)

In [14]:
# 注意：此处是修改了arr1[0]=100之后的输出
s1

0    100
1      8
2      6
3      9
4      1
dtype: int32

In [9]:
# index用来执行Series对象的显示索引，如果没有显示设置索引，则默认使用隐示（数组索引）索引填充
s2 = pd.Series(data=arr1, index=['a', 'b', 'c', 'd', 'e'])
s2

a    6
b    8
c    6
d    9
e    1
dtype: int32

2. From List 使用列表构造 是一个副本对象

In [15]:
list('ABCD')

['A', 'B', 'C', 'D']

In [16]:
l1 = [1,2,3,4]
s3 = pd.Series(data=l1, index=list('ABCD'))
s3

A    1
B    2
C    3
D    4
dtype: int64

In [17]:
l1[0] = 100

In [18]:
l1

[100, 2, 3, 4]

In [19]:
s3

A    1
B    2
C    3
D    4
dtype: int64

3. From dict 使用字典构造

In [20]:
user_info = {
    'name': 'aaa',
    'age': 20,
    'address': 'A'
}

user_info

{'name': 'aaa', 'age': 20, 'address': 'A'}

In [21]:
# 字典构造的Series，默认使用字典的key作为Series的显示索引，values作为Series的值
pd.Series(data=user_info)

name       aaa
age         20
address      A
dtype: object

In [22]:
# NaN not a number 空数值
pd.Series(data=user_info, index=['A', 'B', 'C'])

A    NaN
B    NaN
C    NaN
dtype: object

In [23]:
pd.Series(data=user_info, index=['name', 'address', 'A'])

name       aaa
address      A
A          NaN
dtype: object

4. From scalar value
- 使用一个标量(常量或变量)构造时，必须指定index，标量会被重复匹配到每一个index

In [24]:
index = list('ABCDE')
index

['A', 'B', 'C', 'D', 'E']

In [26]:
data = [6,6,6,6,6]
pd.Series(data=data, index=index)

A    6
B    6
C    6
D    6
E    6
dtype: int64

In [27]:
pd.Series(data=6, index=index)

A    6
B    6
C    6
D    6
E    6
dtype: int64

### 1.2.2 Series属性

- name 返回Series对象的名字

- shape 返回Series对象的形状

- size 返回Series对象的元素个数

- index返回Series对象的显示案引

- values 返回Sereis对象的所有元素值

In [40]:
s = pd.Series(data=[1,2,3], index=list('ABC'), name='111')

In [30]:
s.shape

(3,)

In [31]:
s.index

Index(['A', 'B', 'C'], dtype='object')

In [33]:
s.values

array([1, 2, 3])

In [34]:
# size是元素的个数
s.size

3

In [41]:
s.name

'111'

### 1.2.3 Sereis的数学运算

Series对大多数NumPy的函数都是兼容的

1. 与非pandas对象运算

服从广播机制原则

In [42]:
s + 1

A    2
B    3
C    4
Name: 111, dtype: int64

In [43]:
arr1 = np.array([1,2,3,4])
arr1 + s

ValueError: operands could not be broadcast together with shapes (4,) (3,)

2. NumPy functions

In [44]:
np.power(np.array([1,2,3]), 2)

array([1, 4, 9])

In [45]:
np.power(s,2)

A    1
B    4
C    9
Name: 111, dtype: int64

3. Series之间运算
- 索引对齐原则
- 对不齐补空值，使用addksubimundiv函数处理空值

In [46]:
s

A    1
B    2
C    3
Name: 111, dtype: int64

In [49]:
s1 = pd.Series(data=np.array([2,3,4]), index=['C', 'A', 'B'])
s1

C    2
A    3
B    4
dtype: int64

In [50]:
s + s1

A    4
B    6
C    5
dtype: int64

In [51]:
s2 = pd.Series(data=[2,3,4], index=['A', 'C', 'D'])

In [52]:
s2

A    2
C    3
D    4
dtype: int64

In [53]:
s1 + s2

A    5.0
B    NaN
C    5.0
D    NaN
dtype: float64

## 1.3 DataFrame

DataFrame是一个二维的表格型数据结构，可以看做是由Series组成的字典(共用同一个索引)。

DataFrame由按一定顺序排列的【多列】数据组成，每一列的数类型可能不同。

设计初衷是将Series的使用场最从一维拓展到多维，DataFrame既有行索引，也有列索引。

- 行索引:index
- 列索引:columns
- 值:values(numpy的二维数组)

In [55]:
list1 = [1, 2, 'name']

s1 = pd.Series(data=list1)

In [58]:
# Series和ndarray一样，会强制类型统一
s1

0       1
1       2
2    name
dtype: object

In [57]:
s1.dtype

dtype('O')


### 1.3.1 构造DataFrame

In [59]:
# data-None 用于构造DataFrame的数据
# index=None, columms=None, 行列索引
# dtype=None，数据类型
# copy=False

data = np.random.randint(0, 100, size=(3, 4))
index = ['tom', 'lucy', 'alex']
columns = ['语文', '数学', '英语', '物理']
pd.DataFrame(data=data, index=index, columns=columns)

      语文  数学  英语  物理
tom   63  26   6  62
lucy  10  13  32  11
alex  57   4  40  28

1. From dict of Series or dicts 使用一个由Series构造的字典或一个字典构造

2. From dict ofndarrays/lists 使用一个由列表或ndarray构造的字典构造

ndarrays必须长度保持一致

3. From alist of dicts 使用一个由字典构成的列表构造

In [60]:
names = ['lucy', 'mery', 'tom', 'alex', '智哥']
yuwen =np.random.randint(0,100,size=5)
shuxue = np.random.randint(0,100, size=5)
display(names, yuwen, shuxue)

['lucy', 'mery', 'tom', 'alex', '智哥']

array([74, 39, 70,  9,  9], dtype=int32)

array([42, 25, 18, 24, 35], dtype=int32)

In [61]:
dictionary = {
    'names' : names,
    '语文' : yuwen,
    '数学' : shuxue
}

pd.DataFrame(data=dictionary)

  names  语文  数学
0  lucy  74  42
1  mery  39  25
2   tom  70  18
3  alex   9  24
4    智哥   9  35