# 1 Pandas数据处理

In [1]:
import pandas as pd
import numpy as np

## 1.1 数据IO操作

In [ ]:
fp = open('csv文件.csv', 'r', encoding='utf-8')
fp.read()	I
fp.close()

In [ ]:
with open('csv文件.csv','r',encoding='utf-8')as fp:
    fp.read()

pandas IO操作主要是读取有特定格式的文件

pd.read_csv()

In [5]:
pd.read_csv('csv文件.csv', sep=',', header=None, index_col=0)

       1   2
0
lucy  19  北京
mery  20  上海
tom   22  北京

pd.read_table()

In [7]:
pd.read_table('txt文件.txt', header=None, sep=' ', index_col=0)

       1   2
0
lucy  19  北京
mery  20  上海
tom   22  北京

In [9]:
pd.read_csv('txt文件.txt', sep=' ', header=None)

      0   1   2
0  lucy  19  北京
1  mery  20  上海
2   tom  22  北京

excel读取

In [15]:
data = pd.read_excel('excel文件.xlsx', header=None, names=['姓名','年龄','地址'], sheet_name=0)

In [ ]:
data.to_excel('m_data.xlsx')

In [17]:
data.to_csv('m_data.csv')

## 1.2 数据探索

- describe()
- info()
- head()
- tail()
- sample()

In [19]:
df = pd.DataFrame(data = np.random.randint(0, 10000, size=(10000, 4)), columns= list('ABCD'))
df

         A     B     C     D
0     1092  2961  6457  9163
1     5003  7192  2638   169
2     1771  6915  3687  5876
3     9137  9506  9321  8284
4     8527  4863  5225  8355
...    ...   ...   ...   ...
9995  7388    10  3113  4251
9996  6084  3870  3565   901
9997  3345  5736  8083  5146
9998  2838  6208  3850  3784
9999  4556  6179  1267  8074

[10000 rows x 4 columns]

In [23]:
df.describe(percentiles=[0.25,0.75,0.99])

                  A             B            C             D
count  10000.000000  10000.000000  10000.00000  10000.000000
mean    4989.115400   4992.182700   4945.94810   4990.911600
std     2892.386927   2888.921893   2899.89822   2879.137533
min        0.000000      1.000000      2.00000      1.000000
25%     2494.500000   2470.750000   2425.00000   2515.000000
50%     4969.000000   4963.000000   4913.00000   4979.000000
75%     7506.250000   7529.000000   7436.50000   7481.000000
99%     9892.010000   9903.020000   9897.01000   9900.010000
max     9999.000000   9999.000000   9999.00000   9999.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10000 non-null  int32
 1   B       10000 non-null  int32
 2   C       10000 non-null  int32
 3   D       10000 non-null  int32
dtypes: int32(4)
memory usage: 156.4 KB

## 1.3 空值处理